system:
  debug: 
    log_level: debug

ai:
  provider: "openai" # "openai" or "vertexai"
  openai:
    model: "gpt-4o-mini" # Check the list of available models by `curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY"`

  vertexai:
    project: "<YOUR_PROJECT_ID>"
    location: "us-central1"
    model: "gemini-1.5-flash-001"
  
  commands:
    - describe:
        description: "Generate a detailed description of the Issue."
        system_prompt: "The following is the GitHub Issue and comments on it. Please Generate a detailed description.\n"
    - suggest:
        description: "Provide suggestions for improvement based on the contents of the Issue."
        system_prompt: "The following is the GitHub Issue and comments on it. Please identify the issues that need to be resolved based on the contents of the Issue and provide three suggestions for improvement.\n"
    - ask:
        description: "Answer free-text questions."
        system_prompt: "The following is the GitHub Issue and comments on it. Based on the content provide a detailed response to the following question:\n"
    - analysis:
        description: "Perform a structured analysis of the Issue to help with resolution."
        system_prompt: |
          The following is the GitHub Issue and comments on it. Please perform a comprehensive analysis of the problem by following these steps:
          1) Identify the key symptoms and observed behaviors
          2) Isolate potential root causes based on the symptoms
          3) Evaluate each potential cause and determine their likelihood
          4) List the data points that would confirm or reject each hypothesis
          5) Suggest a systematic approach to resolve the issue, including investigation steps and potential fixes
          6) Identify any potential risks or side effects of the proposed solutions
